// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/kvgossip/serf/serf.proto
// DO NOT EDIT!

/*
Package serf is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/kvgossip/serf/serf.proto

It has these top-level messages:
	SerfQueryMessage
	SerfTreeHashBroadcast
*/
package serf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SerfQueryMessage struct {
	TreeHash  *SerfTreeHashBroadcast `protobuf:"bytes,1,opt,name=tree_hash,json=treeHash" json:"tree_hash,omitempty"`
	HostNonce string                 `protobuf:"bytes,2,opt,name=host_nonce,json=hostNonce" json:"host_nonce,omitempty"`
}

func (m *SerfQueryMessage) Reset()                    { *m = SerfQueryMessage{} }
func (m *SerfQueryMessage) String() string            { return proto.CompactTextString(m) }
func (*SerfQueryMessage) ProtoMessage()               {}
func (*SerfQueryMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SerfQueryMessage) GetTreeHash() *SerfTreeHashBroadcast {
	if m != nil {
		return m.TreeHash
	}
	return nil
}

func (m *SerfQueryMessage) GetHostNonce() string {
	if m != nil {
		return m.HostNonce
	}
	return ""
}

type SerfTreeHashBroadcast struct {
	TreeHash []byte `protobuf:"bytes,1,opt,name=tree_hash,json=treeHash,proto3" json:"tree_hash,omitempty"`
	SyncPort uint32 `protobuf:"varint,2,opt,name=sync_port,json=syncPort" json:"sync_port,omitempty"`
}

func (m *SerfTreeHashBroadcast) Reset()                    { *m = SerfTreeHashBroadcast{} }
func (m *SerfTreeHashBroadcast) String() string            { return proto.CompactTextString(m) }
func (*SerfTreeHashBroadcast) ProtoMessage()               {}
func (*SerfTreeHashBroadcast) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SerfTreeHashBroadcast) GetTreeHash() []byte {
	if m != nil {
		return m.TreeHash
	}
	return nil
}

func (m *SerfTreeHashBroadcast) GetSyncPort() uint32 {
	if m != nil {
		return m.SyncPort
	}
	return 0
}

func init() {
	proto.RegisterType((*SerfQueryMessage)(nil), "serf.SerfQueryMessage")
	proto.RegisterType((*SerfTreeHashBroadcast)(nil), "serf.SerfTreeHashBroadcast")
}

func init() { proto.RegisterFile("github.com/fuserobotics/kvgossip/serf/serf.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x8f, 0x41, 0x4b, 0x80, 0x40,
	0x10, 0x85, 0x31, 0x22, 0xdc, 0xad, 0x20, 0x16, 0x02, 0x41, 0x02, 0xf1, 0xe4, 0x49, 0xa3, 0x2e,
	0x9d, 0x3b, 0x75, 0x29, 0xd2, 0xba, 0xcb, 0xba, 0x8d, 0xae, 0x48, 0x8e, 0xcc, 0x8c, 0x81, 0xff,
	0x3e, 0x76, 0xe9, 0x10, 0xd1, 0x65, 0x18, 0x3e, 0x66, 0xbe, 0xc7, 0xd3, 0xb7, 0xd3, 0x2c, 0x7e,
	0x1f, 0x6a, 0x87, 0x9f, 0xcd, 0xb8, 0x33, 0x10, 0x0e, 0x28, 0xb3, 0xe3, 0x66, 0xf9, 0x9a, 0x90,
	0x79, 0xde, 0x1a, 0x06, 0x1a, 0xe3, 0xa8, 0x37, 0x42, 0x41, 0x73, 0x1a, 0xf6, 0x72, 0xd1, 0x57,
	0x6f, 0x40, 0x63, 0xbb, 0x03, 0x1d, 0xcf, 0xc0, 0x6c, 0x27, 0x30, 0x0f, 0x5a, 0x09, 0x01, 0xf4,
	0xde, 0xb2, 0xcf, 0x92, 0x22, 0xa9, 0xce, 0xef, 0xf2, 0x3a, 0x7e, 0x86, 0xd3, 0x77, 0x02, 0x78,
	0xb2, 0xec, 0x1f, 0x09, 0xed, 0x87, 0xb3, 0x2c, 0x5d, 0x2a, 0x3f, 0xc8, 0xdc, 0x68, 0xed, 0x91,
	0xa5, 0x5f, 0x71, 0x75, 0x90, 0x9d, 0x14, 0x49, 0xa5, 0x3a, 0x15, 0xc8, 0x4b, 0x00, 0x65, 0xab,
	0xaf, 0xff, 0x35, 0x98, 0xfc, 0x6f, 0xe2, 0xc5, 0x2f, 0x69, 0xae, 0x15, 0x1f, 0xab, 0xeb, 0x37,
	0x24, 0x89, 0xce, 0xcb, 0x2e, 0x0d, 0xe0, 0x15, 0x49, 0x86, 0xb3, 0x58, 0xe6, 0xfe, 0x3b, 0x00,
	0x00, 0xff, 0xff, 0x06, 0xa9, 0x92, 0x0f, 0x00, 0x01, 0x00, 0x00,
}
