// Code generated by protoc-gen-gogo.
// source: github.com/fuserobotics/kvgossip/ctl/ctl-service.proto
// DO NOT EDIT!

/*
Package ctl is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/kvgossip/ctl/ctl-service.proto

It has these top-level messages:
	PutGrantRequest
	PutGrantResponse
	BuildTransactionRequest
	BuildTransactionResponse
	PutTransactionRequest
	PutTransactionResponse
	GetGrantsRequest
	GetGrantsResponse
*/
package ctl

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import data "github.com/fuserobotics/kvgossip/data"
import tx "github.com/fuserobotics/kvgossip/tx"
import grant "github.com/fuserobotics/kvgossip/grant"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.GoGoProtoPackageIsVersion1

// Store a new grant in the DB
type PutGrantRequest struct {
	Pool *grant.GrantAuthorizationPool `protobuf:"bytes,1,opt,name=pool" json:"pool,omitempty"`
}

func (m *PutGrantRequest) Reset()                    { *m = PutGrantRequest{} }
func (m *PutGrantRequest) String() string            { return proto.CompactTextString(m) }
func (*PutGrantRequest) ProtoMessage()               {}
func (*PutGrantRequest) Descriptor() ([]byte, []int) { return fileDescriptorCtlService, []int{0} }

func (m *PutGrantRequest) GetPool() *grant.GrantAuthorizationPool {
	if m != nil {
		return m.Pool
	}
	return nil
}

type PutGrantResponse struct {
	Revocations []*data.SignedData `protobuf:"bytes,1,rep,name=revocations" json:"revocations,omitempty"`
}

func (m *PutGrantResponse) Reset()                    { *m = PutGrantResponse{} }
func (m *PutGrantResponse) String() string            { return proto.CompactTextString(m) }
func (*PutGrantResponse) ProtoMessage()               {}
func (*PutGrantResponse) Descriptor() ([]byte, []int) { return fileDescriptorCtlService, []int{1} }

func (m *PutGrantResponse) GetRevocations() []*data.SignedData {
	if m != nil {
		return m.Revocations
	}
	return nil
}

// Request a pool of grants that would satisfy a request.
type BuildTransactionRequest struct {
	EntityPublicKey []byte `protobuf:"bytes,1,opt,name=entity_public_key,json=entityPublicKey,proto3" json:"entity_public_key,omitempty"`
	Key             string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *BuildTransactionRequest) Reset()         { *m = BuildTransactionRequest{} }
func (m *BuildTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*BuildTransactionRequest) ProtoMessage()    {}
func (*BuildTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptorCtlService, []int{2}
}

type BuildTransactionResponse struct {
	Transaction *tx.Transaction    `protobuf:"bytes,1,opt,name=transaction" json:"transaction,omitempty"`
	Revocations []*data.SignedData `protobuf:"bytes,2,rep,name=revocations" json:"revocations,omitempty"`
	Invalid     []*data.SignedData `protobuf:"bytes,3,rep,name=invalid" json:"invalid,omitempty"`
}

func (m *BuildTransactionResponse) Reset()         { *m = BuildTransactionResponse{} }
func (m *BuildTransactionResponse) String() string { return proto.CompactTextString(m) }
func (*BuildTransactionResponse) ProtoMessage()    {}
func (*BuildTransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptorCtlService, []int{3}
}

func (m *BuildTransactionResponse) GetTransaction() *tx.Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *BuildTransactionResponse) GetRevocations() []*data.SignedData {
	if m != nil {
		return m.Revocations
	}
	return nil
}

func (m *BuildTransactionResponse) GetInvalid() []*data.SignedData {
	if m != nil {
		return m.Invalid
	}
	return nil
}

type PutTransactionRequest struct {
	Transaction *tx.Transaction `protobuf:"bytes,1,opt,name=transaction" json:"transaction,omitempty"`
}

func (m *PutTransactionRequest) Reset()                    { *m = PutTransactionRequest{} }
func (m *PutTransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*PutTransactionRequest) ProtoMessage()               {}
func (*PutTransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptorCtlService, []int{4} }

func (m *PutTransactionRequest) GetTransaction() *tx.Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type PutTransactionResponse struct {
}

func (m *PutTransactionResponse) Reset()                    { *m = PutTransactionResponse{} }
func (m *PutTransactionResponse) String() string            { return proto.CompactTextString(m) }
func (*PutTransactionResponse) ProtoMessage()               {}
func (*PutTransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptorCtlService, []int{5} }

type GetGrantsRequest struct {
}

func (m *GetGrantsRequest) Reset()                    { *m = GetGrantsRequest{} }
func (m *GetGrantsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetGrantsRequest) ProtoMessage()               {}
func (*GetGrantsRequest) Descriptor() ([]byte, []int) { return fileDescriptorCtlService, []int{6} }

type GetGrantsResponse struct {
	Grants []*data.SignedData `protobuf:"bytes,1,rep,name=grants" json:"grants,omitempty"`
}

func (m *GetGrantsResponse) Reset()                    { *m = GetGrantsResponse{} }
func (m *GetGrantsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetGrantsResponse) ProtoMessage()               {}
func (*GetGrantsResponse) Descriptor() ([]byte, []int) { return fileDescriptorCtlService, []int{7} }

func (m *GetGrantsResponse) GetGrants() []*data.SignedData {
	if m != nil {
		return m.Grants
	}
	return nil
}

func init() {
	proto.RegisterType((*PutGrantRequest)(nil), "ctl.PutGrantRequest")
	proto.RegisterType((*PutGrantResponse)(nil), "ctl.PutGrantResponse")
	proto.RegisterType((*BuildTransactionRequest)(nil), "ctl.BuildTransactionRequest")
	proto.RegisterType((*BuildTransactionResponse)(nil), "ctl.BuildTransactionResponse")
	proto.RegisterType((*PutTransactionRequest)(nil), "ctl.PutTransactionRequest")
	proto.RegisterType((*PutTransactionResponse)(nil), "ctl.PutTransactionResponse")
	proto.RegisterType((*GetGrantsRequest)(nil), "ctl.GetGrantsRequest")
	proto.RegisterType((*GetGrantsResponse)(nil), "ctl.GetGrantsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ControlService service

type ControlServiceClient interface {
	PutGrant(ctx context.Context, in *PutGrantRequest, opts ...grpc.CallOption) (*PutGrantResponse, error)
	BuildTransaction(ctx context.Context, in *BuildTransactionRequest, opts ...grpc.CallOption) (*BuildTransactionResponse, error)
	PutTransaction(ctx context.Context, in *PutTransactionRequest, opts ...grpc.CallOption) (*PutTransactionResponse, error)
	GetGrants(ctx context.Context, in *GetGrantsRequest, opts ...grpc.CallOption) (*GetGrantsResponse, error)
}

type controlServiceClient struct {
	cc *grpc.ClientConn
}

func NewControlServiceClient(cc *grpc.ClientConn) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) PutGrant(ctx context.Context, in *PutGrantRequest, opts ...grpc.CallOption) (*PutGrantResponse, error) {
	out := new(PutGrantResponse)
	err := grpc.Invoke(ctx, "/ctl.ControlService/PutGrant", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) BuildTransaction(ctx context.Context, in *BuildTransactionRequest, opts ...grpc.CallOption) (*BuildTransactionResponse, error) {
	out := new(BuildTransactionResponse)
	err := grpc.Invoke(ctx, "/ctl.ControlService/BuildTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) PutTransaction(ctx context.Context, in *PutTransactionRequest, opts ...grpc.CallOption) (*PutTransactionResponse, error) {
	out := new(PutTransactionResponse)
	err := grpc.Invoke(ctx, "/ctl.ControlService/PutTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlServiceClient) GetGrants(ctx context.Context, in *GetGrantsRequest, opts ...grpc.CallOption) (*GetGrantsResponse, error) {
	out := new(GetGrantsResponse)
	err := grpc.Invoke(ctx, "/ctl.ControlService/GetGrants", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ControlService service

type ControlServiceServer interface {
	PutGrant(context.Context, *PutGrantRequest) (*PutGrantResponse, error)
	BuildTransaction(context.Context, *BuildTransactionRequest) (*BuildTransactionResponse, error)
	PutTransaction(context.Context, *PutTransactionRequest) (*PutTransactionResponse, error)
	GetGrants(context.Context, *GetGrantsRequest) (*GetGrantsResponse, error)
}

func RegisterControlServiceServer(s *grpc.Server, srv ControlServiceServer) {
	s.RegisterService(&_ControlService_serviceDesc, srv)
}

func _ControlService_PutGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).PutGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ctl.ControlService/PutGrant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).PutGrant(ctx, req.(*PutGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_BuildTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).BuildTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ctl.ControlService/BuildTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).BuildTransaction(ctx, req.(*BuildTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_PutTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).PutTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ctl.ControlService/PutTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).PutTransaction(ctx, req.(*PutTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlService_GetGrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServiceServer).GetGrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ctl.ControlService/GetGrants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServiceServer).GetGrants(ctx, req.(*GetGrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ControlService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ctl.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutGrant",
			Handler:    _ControlService_PutGrant_Handler,
		},
		{
			MethodName: "BuildTransaction",
			Handler:    _ControlService_BuildTransaction_Handler,
		},
		{
			MethodName: "PutTransaction",
			Handler:    _ControlService_PutTransaction_Handler,
		},
		{
			MethodName: "GetGrants",
			Handler:    _ControlService_GetGrants_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptorCtlService,
}

var fileDescriptorCtlService = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0xa5, 0x2d, 0x1a, 0xec, 0x16, 0xad, 0x99, 0xc5, 0x46, 0x15, 0x98, 0x84, 0xfc, 0x34, 0x21,
	0xe1, 0xb2, 0x22, 0x90, 0x90, 0xe0, 0x01, 0x98, 0x98, 0xc4, 0x5e, 0x4a, 0x86, 0xc4, 0xe3, 0x94,
	0x0f, 0x93, 0x59, 0x0b, 0x71, 0x88, 0x6f, 0xa2, 0x95, 0x7f, 0xc4, 0x03, 0xff, 0x11, 0xc7, 0x4e,
	0xda, 0x10, 0x1a, 0x15, 0x1e, 0x12, 0x59, 0xf7, 0x9e, 0x73, 0x7c, 0xcf, 0xb1, 0x0d, 0x2f, 0x63,
	0x81, 0x57, 0x45, 0xc0, 0x42, 0xf9, 0x6d, 0xf6, 0xb5, 0x50, 0x3c, 0x97, 0x81, 0x44, 0x11, 0xaa,
	0xd9, 0x75, 0x19, 0x4b, 0xa5, 0x44, 0x36, 0x0b, 0x31, 0xa9, 0xbe, 0xa7, 0xba, 0x57, 0x8a, 0x90,
	0xb3, 0x2c, 0x97, 0x28, 0xc9, 0x48, 0x97, 0xdc, 0x67, 0x5b, 0xc9, 0x91, 0x8f, 0xbe, 0xf9, 0x59,
	0x9a, 0xfb, 0x62, 0x2b, 0x03, 0x6f, 0x66, 0x98, 0xfb, 0xa9, 0xf2, 0x43, 0x14, 0x32, 0xad, 0x69,
	0xf3, 0xad, 0xb4, 0x58, 0x73, 0xd0, 0xfe, 0x2d, 0x87, 0x9e, 0xc2, 0x64, 0x51, 0xe0, 0x59, 0x55,
	0xf1, 0xf8, 0xf7, 0x82, 0x2b, 0x24, 0x27, 0x70, 0x3b, 0x93, 0x32, 0x99, 0x0e, 0x1e, 0x0f, 0x8e,
	0xc7, 0xf3, 0x23, 0x66, 0xe1, 0x06, 0xf2, 0xb6, 0xc0, 0x2b, 0x99, 0x8b, 0x1f, 0x7e, 0xb5, 0xeb,
	0x42, 0x83, 0x3c, 0x03, 0xa5, 0x1f, 0xc0, 0x59, 0xab, 0xa8, 0x4c, 0xa6, 0x8a, 0x93, 0x39, 0x8c,
	0x73, 0x5e, 0xca, 0xd0, 0x60, 0x95, 0x56, 0x1b, 0x69, 0x35, 0x87, 0x19, 0x9b, 0x17, 0x22, 0x4e,
	0x79, 0x74, 0xaa, 0x97, 0x5e, 0x1b, 0x44, 0xbf, 0xc0, 0x83, 0x77, 0x85, 0x48, 0xa2, 0xcf, 0x6b,
	0x6f, 0xcd, 0x54, 0x4f, 0x60, 0x9f, 0xa7, 0x28, 0x70, 0x79, 0x99, 0x15, 0x41, 0x22, 0xc2, 0xcb,
	0x6b, 0xbe, 0x34, 0x23, 0xde, 0xf3, 0x26, 0xb6, 0xb1, 0x30, 0xf5, 0x73, 0xbe, 0x24, 0x0e, 0x8c,
	0xaa, 0xee, 0x50, 0x77, 0x77, 0xbd, 0x6a, 0x49, 0x7f, 0x0d, 0x60, 0xfa, 0xb7, 0x72, 0x3d, 0xe9,
	0x09, 0x8c, 0x5b, 0x61, 0xd6, 0xbe, 0x27, 0x0c, 0x6f, 0x58, 0x1b, 0xdd, 0xc6, 0x74, 0xcd, 0x0d,
	0xff, 0xc1, 0x9c, 0x76, 0x70, 0x47, 0xa4, 0xa5, 0x9f, 0x88, 0x68, 0x3a, 0xea, 0xc1, 0x37, 0x00,
	0xfa, 0x11, 0x0e, 0x74, 0xa0, 0x1b, 0x62, 0xf8, 0xff, 0x59, 0xe9, 0x14, 0x0e, 0xbb, 0x5a, 0xd6,
	0x38, 0x25, 0xe0, 0x9c, 0x71, 0x7b, 0x6c, 0xaa, 0xde, 0x80, 0xbe, 0x81, 0xfd, 0x56, 0xad, 0x4e,
	0xe8, 0x18, 0x76, 0xcc, 0x2d, 0xe8, 0x3f, 0xc6, 0xba, 0x3f, 0xff, 0x39, 0x84, 0xbd, 0xf7, 0x32,
	0xc5, 0x5c, 0x26, 0x17, 0xf6, 0x29, 0x90, 0x57, 0x70, 0xb7, 0xb9, 0x1c, 0xe4, 0x3e, 0xd3, 0x2f,
	0x82, 0x75, 0x6e, 0x9c, 0x7b, 0xd0, 0xa9, 0xd6, 0xe3, 0xdd, 0x22, 0x9f, 0xc0, 0xe9, 0x9e, 0x1a,
	0x79, 0x64, 0xc0, 0x3d, 0xd7, 0xc4, 0x3d, 0xea, 0xe9, 0xae, 0x24, 0xcf, 0x61, 0xef, 0xcf, 0x34,
	0x88, 0xdb, 0xec, 0xbe, 0x41, 0xee, 0xe1, 0xc6, 0xde, 0x4a, 0xec, 0x35, 0xec, 0xae, 0xc2, 0x22,
	0xd6, 0x45, 0x37, 0x50, 0xf7, 0xb0, 0x5b, 0x6e, 0xd8, 0xc1, 0x8e, 0x79, 0x82, 0xcf, 0x7f, 0x07,
	0x00, 0x00, 0xff, 0xff, 0xea, 0xde, 0xc7, 0x6f, 0x5e, 0x04, 0x00, 0x00,
}
