// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/kvgossip/grant/grant.proto
// DO NOT EDIT!

/*
Package grant is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/kvgossip/grant/grant.proto

It has these top-level messages:
	Grant
	GrantRevocation
	GrantAuthorizationPool
*/
package grant

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import data "github.com/fuserobotics/kvgossip/data"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The actual grant body.
type Grant struct {
	// Regex of allowed keys to change.
	KeyRegex string `protobuf:"bytes,1,opt,name=key_regex,json=keyRegex" json:"key_regex,omitempty"`
	// Do we allow this issuee to grant subgrants of this regex?
	SubgrantAllowed bool `protobuf:"varint,2,opt,name=subgrant_allowed,json=subgrantAllowed" json:"subgrant_allowed,omitempty"`
	// Timestamp we issued this grant.
	IssueTimestamp int64 `protobuf:"varint,3,opt,name=issue_timestamp,json=issueTimestamp" json:"issue_timestamp,omitempty"`
	// Public key of the issuee
	IssueeKey []byte `protobuf:"bytes,4,opt,name=issuee_key,json=issueeKey,proto3" json:"issuee_key,omitempty"`
	// Public key of the issuer
	IssuerKey []byte `protobuf:"bytes,5,opt,name=issuer_key,json=issuerKey,proto3" json:"issuer_key,omitempty"`
}

func (m *Grant) Reset()                    { *m = Grant{} }
func (m *Grant) String() string            { return proto.CompactTextString(m) }
func (*Grant) ProtoMessage()               {}
func (*Grant) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Grant) GetKeyRegex() string {
	if m != nil {
		return m.KeyRegex
	}
	return ""
}

func (m *Grant) GetSubgrantAllowed() bool {
	if m != nil {
		return m.SubgrantAllowed
	}
	return false
}

func (m *Grant) GetIssueTimestamp() int64 {
	if m != nil {
		return m.IssueTimestamp
	}
	return 0
}

func (m *Grant) GetIssueeKey() []byte {
	if m != nil {
		return m.IssueeKey
	}
	return nil
}

func (m *Grant) GetIssuerKey() []byte {
	if m != nil {
		return m.IssuerKey
	}
	return nil
}

type GrantRevocation struct {
	// Timestamp of revocation.
	RevokeTimestamp int64 `protobuf:"varint,1,opt,name=revoke_timestamp,json=revokeTimestamp" json:"revoke_timestamp,omitempty"`
	// Original grant data
	Grant *data.SignedData `protobuf:"bytes,2,opt,name=grant" json:"grant,omitempty"`
}

func (m *GrantRevocation) Reset()                    { *m = GrantRevocation{} }
func (m *GrantRevocation) String() string            { return proto.CompactTextString(m) }
func (*GrantRevocation) ProtoMessage()               {}
func (*GrantRevocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GrantRevocation) GetRevokeTimestamp() int64 {
	if m != nil {
		return m.RevokeTimestamp
	}
	return 0
}

func (m *GrantRevocation) GetGrant() *data.SignedData {
	if m != nil {
		return m.Grant
	}
	return nil
}

type GrantAuthorizationPool struct {
	// All grants that should sum up to the intended operation.
	SignedGrants []*data.SignedData `protobuf:"bytes,1,rep,name=signed_grants,json=signedGrants" json:"signed_grants,omitempty"`
}

func (m *GrantAuthorizationPool) Reset()                    { *m = GrantAuthorizationPool{} }
func (m *GrantAuthorizationPool) String() string            { return proto.CompactTextString(m) }
func (*GrantAuthorizationPool) ProtoMessage()               {}
func (*GrantAuthorizationPool) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GrantAuthorizationPool) GetSignedGrants() []*data.SignedData {
	if m != nil {
		return m.SignedGrants
	}
	return nil
}

func init() {
	proto.RegisterType((*Grant)(nil), "grant.Grant")
	proto.RegisterType((*GrantRevocation)(nil), "grant.GrantRevocation")
	proto.RegisterType((*GrantAuthorizationPool)(nil), "grant.GrantAuthorizationPool")
}

func init() { proto.RegisterFile("github.com/fuserobotics/kvgossip/grant/grant.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x59, 0x6b, 0xa5, 0x5d, 0xab, 0x29, 0x7b, 0x90, 0xa0, 0x08, 0xa1, 0x07, 0x8d, 0x97,
	0x56, 0x2a, 0x3e, 0x40, 0x41, 0xf0, 0xd0, 0x83, 0xb2, 0x7a, 0x0f, 0x9b, 0x66, 0x4c, 0x97, 0xb4,
	0x99, 0xb0, 0xbb, 0x89, 0xc6, 0x07, 0xf3, 0xf9, 0x24, 0xb3, 0x54, 0x7b, 0x10, 0xbc, 0x2c, 0xcc,
	0xf7, 0xcf, 0xcc, 0x3f, 0xfb, 0xf3, 0x79, 0xae, 0xdd, 0xba, 0x4e, 0xa7, 0x2b, 0xdc, 0xce, 0xde,
	0x6a, 0x0b, 0x06, 0x53, 0x74, 0x7a, 0x65, 0x67, 0x45, 0x93, 0xa3, 0xb5, 0xba, 0x9a, 0xe5, 0x46,
	0x95, 0xce, 0xbf, 0xd3, 0xca, 0xa0, 0x43, 0xd1, 0xa7, 0xe2, 0xfc, 0xf6, 0xdf, 0xd1, 0x4c, 0x39,
	0x45, 0x8f, 0x1f, 0x9c, 0x7c, 0x31, 0xde, 0x7f, 0xec, 0x66, 0xc5, 0x05, 0x1f, 0x16, 0xd0, 0x26,
	0x06, 0x72, 0xf8, 0x08, 0x59, 0xc4, 0xe2, 0xa1, 0x1c, 0x14, 0xd0, 0xca, 0xae, 0x16, 0x37, 0x7c,
	0x6c, 0xeb, 0x94, 0x4c, 0x12, 0xb5, 0xd9, 0xe0, 0x3b, 0x64, 0xe1, 0x41, 0xc4, 0xe2, 0x81, 0x0c,
	0x76, 0x7c, 0xe1, 0xb1, 0xb8, 0xe6, 0x81, 0xb6, 0xb6, 0x86, 0xc4, 0xe9, 0x2d, 0x58, 0xa7, 0xb6,
	0x55, 0xd8, 0x8b, 0x58, 0xdc, 0x93, 0xa7, 0x84, 0x5f, 0x77, 0x54, 0x5c, 0x72, 0x4e, 0x04, 0x92,
	0x02, 0xda, 0xf0, 0x30, 0x62, 0xf1, 0x48, 0x0e, 0x3d, 0x59, 0x42, 0xfb, 0x23, 0x1b, 0x92, 0xfb,
	0x7b, 0xb2, 0x59, 0x42, 0x3b, 0xc9, 0x78, 0x40, 0x77, 0x4b, 0x68, 0x70, 0xa5, 0x9c, 0xc6, 0xb2,
	0x3b, 0xd2, 0x40, 0x83, 0xc5, 0xbe, 0x35, 0x23, 0xeb, 0xc0, 0xf3, 0x5f, 0xef, 0x2b, 0xee, 0x13,
	0xa3, 0x4f, 0x1c, 0xcf, 0xc7, 0x53, 0x8a, 0xe4, 0x45, 0xe7, 0x25, 0x64, 0x0f, 0xca, 0x29, 0xe9,
	0xe5, 0xc9, 0x13, 0x3f, 0x23, 0x97, 0x45, 0xed, 0xd6, 0x68, 0xf4, 0x27, 0x19, 0x3d, 0x23, 0x6e,
	0xc4, 0x3d, 0x3f, 0xb1, 0xd4, 0x9e, 0x50, 0xa7, 0x0d, 0x59, 0xd4, 0xfb, 0x73, 0xd3, 0xc8, 0xb7,
	0xd1, 0x1a, 0x9b, 0x1e, 0x51, 0xec, 0x77, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x20, 0x3d,
	0x1b, 0xe5, 0x01, 0x00, 0x00,
}
